### ISSUE TITLE
CompleteWithPreviousQSO  does not deliver correct data

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#723] opened 2024-06-24 06:48 UTC

**Comment by ea5wa** [comment] 2024-06-24 07:19
There is an error in QSO::fromDB that gives an error message in QtCreator: **QSqlQuery::value: not positioned on a valid record**

bool QSO::fromDB(int _qsoId)
{
    logEvent (Q_FUNC_INFO, "Start", Debug);
    QString queryString = "SELECT * FROM log WHERE id=:idQSO";
    QSqlQuery query;
    query.prepare(queryString);
    query.bindValue(":idQSO", _qsoId);

variable _qsoId has the correct value (is pointing correctly to the previous QSO with that callsign) but function fromDB is returning bad data

**Comment by ea4k** [comment] 2024-06-24 07:40
The issue is possibly here: qso::fromDB(int _qsoId)

**Comment by ea5wa** [comment] 2024-06-24 09:51
I think the problem is "idQSO" is not a field of that table. The correct field name is "id".

![image](https://github.com/ea4k/klog/assets/54686689/82085e3c-b94b-437c-9c20-c7184fd6e6b2)

**Comment by ea5wa** [comment] 2024-06-24 11:11
Finally it was a problem with the data inside my logbook.dat. It was filled with erroneous data. 

There is no issue with KLog Code, previousQSO is correctly presenting the data. **You can close this issue**.

Sorry

**Closed as completed** 2024-06-24 21:28 UTC
Labels: bug, ToBeConfirmed
