### ISSUE TITLE
Frequency setting text box usability

### ISSUE THREAD

**Issue by SpudGunMan** [ea4k/klog#588] opened 2023-05-10 06:04 UTC
I find the way the text box functions along with the RST box hard to deal with in Linux. It's like computational forces are checking each digit (possibly to send to hamlib etc) 

It's not possible to just type in a frequency need to modify each character

**Comment by conorpeterson** [comment] 2023-05-15 15:52
This is a duplicate of issue #378.

**Comment by ea4k** [comment] 2023-12-11 17:14
Duplicated #378

**Closed as completed by ea4k** 2023-12-11 17:14 UTC
Labels: bug, ToBeConfirmed
